language: php

php:
  - hhvm
  
branches:
  only:
    - master
    - /^\d+\.\d+$/

before_script:
  - composer self-update
  - sh -c 'if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi;'
  - composer update --prefer-source

script: phpunit --coverage-clover=coverage.clover

